language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: false


# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install --pre -r requirements.txt"
  - mkdir -p test/input test/tmp
  - wget -P test/input https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png

# command to run test
script:
  - python asciizer.py -h
  - python test_asciizer.py

